format:
	prettier index.html --quote-props consistent --write --print-width 100 --tab-width 4
	prettier main.css --quote-props consistent --write --print-width 100 --tab-width 4
	prettier main.js --quote-props consistent --write --print-width 100 --tab-width 4
